version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT:-8080}:${BACKEND_PORT:-8080}"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-dev}
      - POSTGRES_HOST=${POSTGRES_HOST:-postgres}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - MAIL_HOST=${MAIL_HOST:-mailhog}
      - MAIL_PORT=${MAIL_PORT:-1025}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:5173}
      - BACKEND_URL=${BACKEND_URL:-http://localhost:8080}
    networks:
      - app_network
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    extends:
      file: ./database/docker-compose.yml
      service: postgres
    networks:
      - app_network

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"  # SMTP Server
      - "8025:8025"  # Web UI
    networks:
      - app_network

networks:
  app_network:
    name: ${NETWORK_NAME}
    driver: bridge 