spring:
  datasource:
    url: jdbc:postgresql://google/${POSTGRES_DB}?cloudSqlInstance=${CLOUD_SQL_INSTANCE}&socketFactory=com.google.cloud.sql.postgres.SocketFactory&useSSL=true
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1
      connection-timeout: 60000
      initialization-fail-timeout: 60000
      validation-timeout: 10000

  jpa:
    show-sql: false
    
server:
  address: 0.0.0.0 